version: 1.0

database:
  default_admin: "Leavin_Suika"
  default_admin_pwd: "password"

api:
  get_api: "https://music-api.gdstudio.xyz/api.php?types=url&source={source}&id={track_id}"

connection:
  heartbeat_timeout: 60
  host: "0.0.0.0"
  port: 8001